# Generated by Django 5.2.6 on 2026-03-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_bankconnection_transaction_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('checking', 'Checking'), ('savings', 'Savings'), ('credit', 'Credit Card'), ('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('investment', 'Investment')], default='checking', max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(default='TZS', max_length=3),
        ),
    ]
